pipeline {
    agent any
    
    tools {
        maven 'maven-3.9.4'
    }
    
    stages {
        
        stage('Checkout GIT') {
            steps {
                echo 'Récupération du code depuis GitHub...'
            }
        }
        
        stage('Maven Build') {
            steps {
                echo 'Compilation Maven...'
                dir('achat/achat') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        
        stage('Maven Test') {
            steps {
                echo 'Tests unitaires...'
                dir('achat/achat') {
                    sh 'mvn test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('achat/achat') {
                    withSonarQubeEnv('SonarQube') {
                        sh 'mvn sonar:sonar -Dsonar.projectKey=achat-devops'
                    }
                }
            }
        }
        
    }
    
    post {
        success {
            echo 'Build réussi !'
        }
        failure {
            echo 'Build échoué !'
        }
    }
}